name: sessions_wellness
version: 1.0.0
config-version: 2

profile: sessions_wellness

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sessions_wellness:
    +materialized: view
    staging:
      +schema: stg_sessions_wellness
      +materialized: view
    marts:
      +schema: mart_sessions_wellness
      +materialized: table
