"""Initial schema

Revision ID: 66a6bcbaa092
Revises: 
Create Date: 2025-10-20 12:20:22.978659

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '66a6bcbaa092'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_data',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('contributing_orgs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_data_age_group'), 'benchmark_data', ['age_group'], unique=False)
    op.create_index(op.f('ix_benchmark_data_role'), 'benchmark_data', ['role'], unique=False)
    op.create_table('drift_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('check_date', sa.DateTime(), nullable=False),
    sa.Column('psi_carichi', sa.Float(), nullable=False),
    sa.Column('psi_wellness', sa.Float(), nullable=False),
    sa.Column('psi_psicologico', sa.Float(), nullable=False),
    sa.Column('psi_kpi_tecnici', sa.Float(), nullable=False),
    sa.Column('mae_current', sa.Float(), nullable=False),
    sa.Column('mae_baseline', sa.Float(), nullable=False),
    sa.Column('mae_degradation_pct', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('actions_taken', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('match_type', sa.Enum('LEAGUE', 'CUP', 'FRIENDLY', 'TRAINING_MATCH', name='matchtype'), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('opponent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('WIN', 'DRAW', 'LOSS', 'NOT_PLAYED', name='matchresult'), nullable=False),
    sa.Column('venue', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weather', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('video_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_organization_id'), 'matches', ['organization_id'], unique=False)
    op.create_index(op.f('ix_matches_team_id'), 'matches', ['team_id'], unique=False)
    op.create_index(op.f('ix_matches_video_id'), 'matches', ['video_id'], unique=False)
    op.create_table('ml_model_versions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('features_count', sa.Integer(), nullable=False),
    sa.Column('features_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('auc', sa.Float(), nullable=True),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('model_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('organizations',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('benchmark_opt_in', sa.Boolean(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quota_players', sa.Integer(), nullable=False),
    sa.Column('quota_storage_gb', sa.Integer(), nullable=False),
    sa.Column('current_storage_gb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('training_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_date', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.Enum('TRAINING', 'FRIENDLY', 'RECOVERY', 'GYM', 'TACTICAL', name='sessiontype'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('focus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_intensity', sa.Integer(), nullable=True),
    sa.Column('actual_intensity_avg', sa.Float(), nullable=True),
    sa.Column('video_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('hi_distance_m', sa.Float(), nullable=True),
    sa.Column('sprints_count', sa.Integer(), nullable=True),
    sa.Column('top_speed_ms', sa.Float(), nullable=True),
    sa.Column('max_acc_ms2', sa.Float(), nullable=True),
    sa.Column('hr_avg_bpm', sa.Integer(), nullable=True),
    sa.Column('hr_max_bpm', sa.Integer(), nullable=True),
    sa.Column('fatigue_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_organization_id'), 'training_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_team_id'), 'training_sessions', ['team_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_video_id'), 'training_sessions', ['video_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_mb', sa.Float(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('keyframes_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pose_data_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('heatmap_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('events_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_match_id'), 'videos', ['match_id'], unique=False)
    op.create_index(op.f('ix_videos_organization_id'), 'videos', ['organization_id'], unique=False)
    op.create_index(op.f('ix_videos_session_id'), 'videos', ['session_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_organization_id'), 'seasons', ['organization_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_index(op.f('ix_teams_season_id'), 'teams', ['season_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('guardian_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guardian_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role_primary', sa.Enum('GK', 'DF', 'MF', 'FW', name='playerrole'), nullable=False),
    sa.Column('role_secondary', sa.Enum('GK', 'DF', 'MF', 'FW', name='playerrole'), nullable=True),
    sa.Column('dominant_foot', sa.Enum('LEFT', 'RIGHT', 'BOTH', name='dominantfoot'), nullable=False),
    sa.Column('dominant_arm', sa.Enum('LEFT', 'RIGHT', name='dominantarm'), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('lean_mass_kg', sa.Float(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.DateTime(), nullable=True),
    sa.Column('consent_parent_given', sa.Boolean(), nullable=True),
    sa.Column('data_retention_until', sa.Date(), nullable=True),
    sa.Column('medical_clearance', sa.Boolean(), nullable=False),
    sa.Column('medical_clearance_expiry', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_injured', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_organization_id'), 'players', ['organization_id'], unique=False)
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_card', sa.Boolean(), nullable=False),
    sa.Column('coach_rating', sa.Float(), nullable=True),
    sa.Column('analyst_rating', sa.Float(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_match_id'), 'attendances', ['match_id'], unique=False)
    op.create_index(op.f('ix_attendances_organization_id'), 'attendances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendances_player_id'), 'attendances', ['player_id'], unique=False)
    op.create_table('daily_readiness',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('sleep_score', sa.Float(), nullable=True),
    sa.Column('hrv_score', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('wellness_score', sa.Float(), nullable=True),
    sa.Column('workload_score', sa.Float(), nullable=True),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('doms_rating', sa.Integer(), nullable=True),
    sa.Column('fatigue_rating', sa.Integer(), nullable=True),
    sa.Column('stress_rating', sa.Integer(), nullable=True),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('yesterday_training_load', sa.Float(), nullable=True),
    sa.Column('acute_chronic_ratio', sa.Float(), nullable=True),
    sa.Column('recommended_training_intensity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('can_train_full', sa.Boolean(), nullable=False),
    sa.Column('injury_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('predicted_performance_today', sa.Float(), nullable=True),
    sa.Column('injury_risk_probability', sa.Float(), nullable=True),
    sa.Column('coach_override', sa.Boolean(), nullable=False),
    sa.Column('coach_override_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_readiness_organization_id'), 'daily_readiness', ['organization_id'], unique=False)
    op.create_index(op.f('ix_daily_readiness_player_id'), 'daily_readiness', ['player_id'], unique=False)
    op.create_table('health_monitoring',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'INJURED', 'RECOVERING', 'ILLNESS', name='healthstatus'), nullable=False),
    sa.Column('injury_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('injury_start', sa.Date(), nullable=True),
    sa.Column('injury_end', sa.Date(), nullable=True),
    sa.Column('weekly_load_AU', sa.Float(), nullable=True),
    sa.Column('injury_risk_0_1', sa.Float(), nullable=True),
    sa.Column('avg_sleep_quality_1_5', sa.Float(), nullable=True),
    sa.Column('nutrition_hydration_1_5', sa.Integer(), nullable=True),
    sa.Column('pain_1_10', sa.Integer(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_monitoring_organization_id'), 'health_monitoring', ['organization_id'], unique=False)
    op.create_index(op.f('ix_health_monitoring_player_id'), 'health_monitoring', ['player_id'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('injury_date', sa.Date(), nullable=False),
    sa.Column('injury_type', sa.Enum('MUSCLE', 'LIGAMENT', 'TENDON', 'BONE', 'JOINT', 'CONCUSSION', 'OTHER', name='injurytype'), nullable=False),
    sa.Column('body_part', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_side', sa.Enum('LEFT', 'RIGHT', 'BILATERAL', 'NA', name='bodyside'), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MODERATE', 'SEVERE', name='injuryseverity'), nullable=False),
    sa.Column('mechanism', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('days_out', sa.Integer(), nullable=True),
    sa.Column('is_recurrence', sa.Boolean(), nullable=False),
    sa.Column('previous_injury_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('medical_clearance', sa.Boolean(), nullable=False),
    sa.Column('clearance_date', sa.Date(), nullable=True),
    sa.Column('doctor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['previous_injury_id'], ['injuries.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_organization_id'), 'injuries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_table('match_player_stats',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('substituted_in_min', sa.Integer(), nullable=True),
    sa.Column('substituted_out_min', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('hi_distance_m', sa.Float(), nullable=True),
    sa.Column('sprints_count', sa.Integer(), nullable=True),
    sa.Column('top_speed_kmh', sa.Float(), nullable=True),
    sa.Column('accelerations', sa.Integer(), nullable=True),
    sa.Column('decelerations', sa.Integer(), nullable=True),
    sa.Column('passes_completed', sa.Integer(), nullable=False),
    sa.Column('passes_attempted', sa.Integer(), nullable=False),
    sa.Column('pass_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('shots_on_target', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('dribbles_completed', sa.Integer(), nullable=False),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=False),
    sa.Column('crosses_completed', sa.Integer(), nullable=False),
    sa.Column('crosses_attempted', sa.Integer(), nullable=False),
    sa.Column('tackles', sa.Integer(), nullable=False),
    sa.Column('interceptions', sa.Integer(), nullable=False),
    sa.Column('clearances', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.Integer(), nullable=False),
    sa.Column('duels_won', sa.Integer(), nullable=False),
    sa.Column('duels_lost', sa.Integer(), nullable=False),
    sa.Column('fouls_committed', sa.Integer(), nullable=False),
    sa.Column('fouls_won', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('touches', sa.Integer(), nullable=True),
    sa.Column('possession_won', sa.Integer(), nullable=True),
    sa.Column('possession_lost', sa.Integer(), nullable=True),
    sa.Column('opponent_team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('opponent_difficulty', sa.Integer(), nullable=True),
    sa.Column('coach_rating', sa.Float(), nullable=True),
    sa.Column('team_avg_rating', sa.Float(), nullable=True),
    sa.Column('performance_index', sa.Float(), nullable=True),
    sa.Column('stats_by_half', sa.Text(), nullable=True),
    sa.Column('heatmap_data', sa.Text(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_player_stats_match_id'), 'match_player_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_player_stats_organization_id'), 'match_player_stats', ['organization_id'], unique=False)
    op.create_index(op.f('ix_match_player_stats_player_id'), 'match_player_stats', ['player_id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('expected_performance', sa.Float(), nullable=False),
    sa.Column('confidence_lower', sa.Float(), nullable=False),
    sa.Column('confidence_upper', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Enum('ATTENTION', 'NEUTRAL', 'GROWING', name='thresholdlevel'), nullable=False),
    sa.Column('overload_risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='overloadrisklevel'), nullable=False),
    sa.Column('overload_probability', sa.Float(), nullable=False),
    sa.Column('overload_confidence_lower', sa.Float(), nullable=False),
    sa.Column('overload_confidence_upper', sa.Float(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_health', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature_importances', sa.JSON(), nullable=True),
    sa.Column('local_contributions', sa.JSON(), nullable=True),
    sa.Column('natural_language_explanation', sa.Text(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_organization_id'), 'ml_predictions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_player_id'), 'ml_predictions', ['player_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('period_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('physical_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('tactical_score', sa.Float(), nullable=True),
    sa.Column('psychological_score', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('form_index', sa.Float(), nullable=True),
    sa.Column('physical_percentile', sa.Float(), nullable=True),
    sa.Column('technical_percentile', sa.Float(), nullable=True),
    sa.Column('tactical_percentile', sa.Float(), nullable=True),
    sa.Column('team_rank_physical', sa.Integer(), nullable=True),
    sa.Column('team_rank_technical', sa.Integer(), nullable=True),
    sa.Column('team_rank_overall', sa.Integer(), nullable=True),
    sa.Column('physical_zscore', sa.Float(), nullable=True),
    sa.Column('technical_zscore', sa.Float(), nullable=True),
    sa.Column('tactical_zscore', sa.Float(), nullable=True),
    sa.Column('trend_3m', sa.Integer(), nullable=True),
    sa.Column('trend_6m', sa.Integer(), nullable=True),
    sa.Column('metrics_summary', sa.Text(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_organization_id'), 'performance_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_player_id'), 'performance_snapshots', ['player_id'], unique=False)
    op.create_table('physical_tests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('lean_mass_kg', sa.Float(), nullable=True),
    sa.Column('vo2max_ml_kg_min', sa.Float(), nullable=True),
    sa.Column('cooper_test_m', sa.Float(), nullable=True),
    sa.Column('yoyo_test_level', sa.Float(), nullable=True),
    sa.Column('vam_km_h', sa.Float(), nullable=True),
    sa.Column('sprint_10m_s', sa.Float(), nullable=True),
    sa.Column('sprint_20m_s', sa.Float(), nullable=True),
    sa.Column('sprint_30m_s', sa.Float(), nullable=True),
    sa.Column('rsa_best_s', sa.Float(), nullable=True),
    sa.Column('cod_505_s', sa.Float(), nullable=True),
    sa.Column('illinois_s', sa.Float(), nullable=True),
    sa.Column('cmj_cm', sa.Float(), nullable=True),
    sa.Column('sj_cm', sa.Float(), nullable=True),
    sa.Column('cmj_left_cm', sa.Float(), nullable=True),
    sa.Column('cmj_right_cm', sa.Float(), nullable=True),
    sa.Column('sit_and_reach_cm', sa.Float(), nullable=True),
    sa.Column('ankle_dorsiflexion_deg', sa.Float(), nullable=True),
    sa.Column('fms_score', sa.Integer(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tester_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_tests_organization_id'), 'physical_tests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_physical_tests_player_id'), 'physical_tests', ['player_id'], unique=False)
    op.create_table('psychological_profile',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('motivation_1_5', sa.Integer(), nullable=True),
    sa.Column('self_esteem_1_5', sa.Integer(), nullable=True),
    sa.Column('leadership_1_5', sa.Integer(), nullable=True),
    sa.Column('resilience_1_5', sa.Integer(), nullable=True),
    sa.Column('stress_mgmt_1_5', sa.Integer(), nullable=True),
    sa.Column('mental_fatigue_1_5', sa.Integer(), nullable=True),
    sa.Column('coach_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychological_profile_organization_id'), 'psychological_profile', ['organization_id'], unique=False)
    op.create_index(op.f('ix_psychological_profile_player_id'), 'psychological_profile', ['player_id'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('hi_runs', sa.Integer(), nullable=True),
    sa.Column('sprint_count', sa.Integer(), nullable=True),
    sa.Column('top_speed_km_h', sa.Float(), nullable=True),
    sa.Column('accelerations', sa.Integer(), nullable=True),
    sa.Column('decelerations', sa.Integer(), nullable=True),
    sa.Column('player_load', sa.Float(), nullable=True),
    sa.Column('hr_avg_bpm', sa.Integer(), nullable=True),
    sa.Column('hr_peak_bpm', sa.Integer(), nullable=True),
    sa.Column('time_zone_1_sec', sa.Integer(), nullable=True),
    sa.Column('time_zone_2_sec', sa.Integer(), nullable=True),
    sa.Column('time_zone_3_sec', sa.Integer(), nullable=True),
    sa.Column('time_zone_4_sec', sa.Integer(), nullable=True),
    sa.Column('time_zone_5_sec', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('data_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_match_id'), 'sensor_data', ['match_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_organization_id'), 'sensor_data', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_player_id'), 'sensor_data', ['player_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_session_id'), 'sensor_data', ['session_id'], unique=False)
    op.create_table('tactical_cognitive',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('involvement_pct', sa.Float(), nullable=True),
    sa.Column('reaction_time_ms', sa.Float(), nullable=True),
    sa.Column('correct_decisions_pct', sa.Float(), nullable=True),
    sa.Column('anticipations_pct', sa.Float(), nullable=True),
    sa.Column('pressing_timing_ms', sa.Float(), nullable=True),
    sa.Column('cognitive_errors', sa.Integer(), nullable=True),
    sa.Column('centroid_x_pct', sa.Float(), nullable=True),
    sa.Column('centroid_y_pct', sa.Float(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactical_cognitive_organization_id'), 'tactical_cognitive', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tactical_cognitive_player_id'), 'tactical_cognitive', ['player_id'], unique=False)
    op.create_table('tactical_tests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('avg_position_x', sa.Float(), nullable=True),
    sa.Column('avg_position_y', sa.Float(), nullable=True),
    sa.Column('position_variance', sa.Float(), nullable=True),
    sa.Column('recoveries', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('clearances', sa.Integer(), nullable=True),
    sa.Column('pressing_actions', sa.Integer(), nullable=True),
    sa.Column('decision_making_rating', sa.Float(), nullable=True),
    sa.Column('attention_rating', sa.Float(), nullable=True),
    sa.Column('anticipation_rating', sa.Float(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactical_tests_organization_id'), 'tactical_tests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tactical_tests_player_id'), 'tactical_tests', ['player_id'], unique=False)
    op.create_table('technical_stats',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pass_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('conversion_rate_pct', sa.Float(), nullable=True),
    sa.Column('dribbles_won', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('duels_lost', sa.Integer(), nullable=True),
    sa.Column('crosses_successful', sa.Integer(), nullable=True),
    sa.Column('crosses_attempted', sa.Integer(), nullable=True),
    sa.Column('unforced_errors', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('weak_foot_usage_pct', sa.Float(), nullable=True),
    sa.Column('decision_time_ms', sa.Float(), nullable=True),
    sa.Column('heatmap_json', sa.Text(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_stats_organization_id'), 'technical_stats', ['organization_id'], unique=False)
    op.create_index(op.f('ix_technical_stats_player_id'), 'technical_stats', ['player_id'], unique=False)
    op.create_table('technical_tests',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('match_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('passes_completed', sa.Integer(), nullable=True),
    sa.Column('passes_attempted', sa.Integer(), nullable=True),
    sa.Column('passing_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('progressive_passes', sa.Integer(), nullable=True),
    sa.Column('dribbles_completed', sa.Integer(), nullable=True),
    sa.Column('dribbles_attempted', sa.Integer(), nullable=True),
    sa.Column('dribbling_success_pct', sa.Float(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('shots_attempted', sa.Integer(), nullable=True),
    sa.Column('shooting_accuracy_pct', sa.Float(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('crosses_completed', sa.Integer(), nullable=True),
    sa.Column('crosses_attempted', sa.Integer(), nullable=True),
    sa.Column('duels_won', sa.Integer(), nullable=True),
    sa.Column('duels_total', sa.Integer(), nullable=True),
    sa.Column('duels_win_pct', sa.Float(), nullable=True),
    sa.Column('first_touch_success', sa.Integer(), nullable=True),
    sa.Column('first_touch_attempts', sa.Integer(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_tests_organization_id'), 'technical_tests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_technical_tests_player_id'), 'technical_tests', ['player_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_areas', sa.JSON(), nullable=True),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_organization_id'), 'training_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_training_plans_player_id'), 'training_plans', ['player_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'COACH', 'ANALYST', 'PHYSIO', 'DOCTOR', 'PLAYER', 'PARENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_player_id'), 'users', ['player_id'], unique=False)
    op.create_table('video_events',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('video_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('event_type', sa.Enum('SHOT', 'PASS', 'CROSS', 'DRIBBLE', 'TACKLE', 'INTERCEPTION', 'CLEARANCE', 'GOAL', 'ASSIST', 'FOUL', 'OFFSIDE', 'CORNER', 'FREE_KICK', 'THROW_IN', name='eventtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_events_organization_id'), 'video_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_video_events_player_id'), 'video_events', ['player_id'], unique=False)
    op.create_index(op.f('ix_video_events_video_id'), 'video_events', ['video_id'], unique=False)
    op.create_table('wellness_data',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('sleep_start_hhmm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('wake_time_hhmm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_weight_kg', sa.Float(), nullable=True),
    sa.Column('hrv_ms', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Integer(), nullable=True),
    sa.Column('doms_rating', sa.Integer(), nullable=True),
    sa.Column('fatigue_rating', sa.Integer(), nullable=True),
    sa.Column('stress_rating', sa.Integer(), nullable=True),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('motivation_rating', sa.Integer(), nullable=True),
    sa.Column('hydration_rating', sa.Integer(), nullable=True),
    sa.Column('hydration_pct', sa.Float(), nullable=True),
    sa.Column('srpe', sa.Integer(), nullable=True),
    sa.Column('session_duration_min', sa.Integer(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wellness_data_organization_id'), 'wellness_data', ['organization_id'], unique=False)
    op.create_index(op.f('ix_wellness_data_player_id'), 'wellness_data', ['player_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', 'LOGIN', 'LOGOUT', 'ACCESS_DENIED', name='auditaction'), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('automated_insights',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('team_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('insight_type', sa.Enum('PERFORMANCE_DROP', 'PERFORMANCE_PEAK', 'INJURY_RISK', 'WELLNESS_ALERT', 'GOAL_PROGRESS', 'TRAINING_LOAD', 'TECHNICAL_IMPROVEMENT', 'TACTICAL_IMPROVEMENT', 'COMPARISON', name='insighttype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='insightpriority'), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('actionable_recommendation', sa.Text(), nullable=True),
    sa.Column('supporting_data', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('statistical_significance', sa.Float(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('comparison_baseline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('read_by_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('coach_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['read_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automated_insights_organization_id'), 'automated_insights', ['organization_id'], unique=False)
    op.create_index(op.f('ix_automated_insights_player_id'), 'automated_insights', ['player_id'], unique=False)
    op.create_index(op.f('ix_automated_insights_team_id'), 'automated_insights', ['team_id'], unique=False)
    op.create_table('plan_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('plan_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('area', sa.Enum('TECHNICAL', 'TACTICAL_COGNITIVE', 'PHYSICAL', 'PSYCHOLOGICAL', 'LIFESTYLE_RECOVERY', 'MEDICAL_PREVENTION', name='trainingarea'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metric', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'PARTIAL', 'SKIPPED', name='taskstatus'), nullable=False),
    sa.Column('completion_pct', sa.Float(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_tasks_organization_id'), 'plan_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_plan_tasks_plan_id'), 'plan_tasks', ['plan_id'], unique=False)
    op.create_table('player_goals',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('category', sa.Enum('PHYSICAL', 'TECHNICAL', 'TACTICAL', 'PSYCHOLOGICAL', 'HEALTH', name='goalcategory'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('on_track', sa.Boolean(), nullable=True),
    sa.Column('milestones', sa.Text(), nullable=True),
    sa.Column('predicted_completion_probability', sa.Float(), nullable=True),
    sa.Column('predicted_final_value', sa.Float(), nullable=True),
    sa.Column('assigned_by_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('coach_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_goals_organization_id'), 'player_goals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_player_goals_player_id'), 'player_goals', ['player_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('report_type', sa.Enum('PLAYER', 'TEAM', 'STAFF_WEEKLY', name='reporttype'), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'HTML', 'JSON', name='reportformat'), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('team_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('range_start', sa.DateTime(), nullable=False),
    sa.Column('range_end', sa.DateTime(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size_kb', sa.Float(), nullable=False),
    sa.Column('generated_by', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('generation_duration_sec', sa.Float(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_player_id'), 'reports', ['player_id'], unique=False)
    op.create_index(op.f('ix_reports_team_id'), 'reports', ['team_id'], unique=False)
    op.create_table('plan_adherences',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'PARTIAL', 'SKIPPED', name='taskstatus'), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['plan_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_adherences_organization_id'), 'plan_adherences', ['organization_id'], unique=False)
    op.create_index(op.f('ix_plan_adherences_player_id'), 'plan_adherences', ['player_id'], unique=False)
    op.create_index(op.f('ix_plan_adherences_task_id'), 'plan_adherences', ['task_id'], unique=False)
    op.create_table('report_caches',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index(op.f('ix_report_caches_report_id'), 'report_caches', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_caches_report_id'), table_name='report_caches')
    op.drop_table('report_caches')
    op.drop_index(op.f('ix_plan_adherences_task_id'), table_name='plan_adherences')
    op.drop_index(op.f('ix_plan_adherences_player_id'), table_name='plan_adherences')
    op.drop_index(op.f('ix_plan_adherences_organization_id'), table_name='plan_adherences')
    op.drop_table('plan_adherences')
    op.drop_index(op.f('ix_reports_team_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_player_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_player_goals_player_id'), table_name='player_goals')
    op.drop_index(op.f('ix_player_goals_organization_id'), table_name='player_goals')
    op.drop_table('player_goals')
    op.drop_index(op.f('ix_plan_tasks_plan_id'), table_name='plan_tasks')
    op.drop_index(op.f('ix_plan_tasks_organization_id'), table_name='plan_tasks')
    op.drop_table('plan_tasks')
    op.drop_index(op.f('ix_automated_insights_team_id'), table_name='automated_insights')
    op.drop_index(op.f('ix_automated_insights_player_id'), table_name='automated_insights')
    op.drop_index(op.f('ix_automated_insights_organization_id'), table_name='automated_insights')
    op.drop_table('automated_insights')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_wellness_data_player_id'), table_name='wellness_data')
    op.drop_index(op.f('ix_wellness_data_organization_id'), table_name='wellness_data')
    op.drop_table('wellness_data')
    op.drop_index(op.f('ix_video_events_video_id'), table_name='video_events')
    op.drop_index(op.f('ix_video_events_player_id'), table_name='video_events')
    op.drop_index(op.f('ix_video_events_organization_id'), table_name='video_events')
    op.drop_table('video_events')
    op.drop_index(op.f('ix_users_player_id'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_plans_player_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_organization_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_technical_tests_player_id'), table_name='technical_tests')
    op.drop_index(op.f('ix_technical_tests_organization_id'), table_name='technical_tests')
    op.drop_table('technical_tests')
    op.drop_index(op.f('ix_technical_stats_player_id'), table_name='technical_stats')
    op.drop_index(op.f('ix_technical_stats_organization_id'), table_name='technical_stats')
    op.drop_table('technical_stats')
    op.drop_index(op.f('ix_tactical_tests_player_id'), table_name='tactical_tests')
    op.drop_index(op.f('ix_tactical_tests_organization_id'), table_name='tactical_tests')
    op.drop_table('tactical_tests')
    op.drop_index(op.f('ix_tactical_cognitive_player_id'), table_name='tactical_cognitive')
    op.drop_index(op.f('ix_tactical_cognitive_organization_id'), table_name='tactical_cognitive')
    op.drop_table('tactical_cognitive')
    op.drop_index(op.f('ix_sensor_data_session_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_player_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_organization_id'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_match_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index(op.f('ix_psychological_profile_player_id'), table_name='psychological_profile')
    op.drop_index(op.f('ix_psychological_profile_organization_id'), table_name='psychological_profile')
    op.drop_table('psychological_profile')
    op.drop_index(op.f('ix_physical_tests_player_id'), table_name='physical_tests')
    op.drop_index(op.f('ix_physical_tests_organization_id'), table_name='physical_tests')
    op.drop_table('physical_tests')
    op.drop_index(op.f('ix_performance_snapshots_player_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_organization_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_ml_predictions_player_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_organization_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_match_player_stats_player_id'), table_name='match_player_stats')
    op.drop_index(op.f('ix_match_player_stats_organization_id'), table_name='match_player_stats')
    op.drop_index(op.f('ix_match_player_stats_match_id'), table_name='match_player_stats')
    op.drop_table('match_player_stats')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_organization_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_health_monitoring_player_id'), table_name='health_monitoring')
    op.drop_index(op.f('ix_health_monitoring_organization_id'), table_name='health_monitoring')
    op.drop_table('health_monitoring')
    op.drop_index(op.f('ix_daily_readiness_player_id'), table_name='daily_readiness')
    op.drop_index(op.f('ix_daily_readiness_organization_id'), table_name='daily_readiness')
    op.drop_table('daily_readiness')
    op.drop_index(op.f('ix_attendances_player_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_organization_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_match_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_index(op.f('ix_players_organization_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_teams_season_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_seasons_organization_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_videos_session_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_organization_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_match_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_training_sessions_video_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_team_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_organization_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('ml_model_versions')
    op.drop_index(op.f('ix_matches_video_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_organization_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('drift_metrics')
    op.drop_index(op.f('ix_benchmark_data_role'), table_name='benchmark_data')
    op.drop_index(op.f('ix_benchmark_data_age_group'), table_name='benchmark_data')
    op.drop_table('benchmark_data')
    # ### end Alembic commands ###
