"""Training Plan schemas for request/response."""

from datetime import date, datetime
from typing import Optional
from uuid import UUID

from pydantic import BaseModel, Field

from app.models.plan import TaskStatus, TrainingArea


# ============================================
# TRAINING PLAN SCHEMAS
# ============================================


class TrainingPlanBase(BaseModel):
    """Base training plan schema."""

    player_id: UUID = Field(..., description="Player ID")
    week_start: date = Field(..., description="Week start date")
    week_end: date = Field(..., description="Week end date")
    is_active: bool = Field(True, description="Whether the plan is active")
    target_areas: list[str] = Field(default=[], description="Target training areas")


class TrainingPlanCreate(TrainingPlanBase):
    """Schema for creating a training plan."""

    organization_id: UUID = Field(..., description="Organization ID")
    generated_by: str = Field("manual", description="How the plan was generated")
    model_version: Optional[str] = Field(None, description="ML model version if generated by ML")
    confidence: Optional[float] = Field(None, ge=0, le=1, description="Confidence score if ML-generated")


class TrainingPlanUpdate(BaseModel):
    """Schema for updating a training plan."""

    week_start: Optional[date] = None
    week_end: Optional[date] = None
    is_active: Optional[bool] = None
    target_areas: Optional[list[str]] = None


class TrainingPlanResponse(TrainingPlanBase):
    """Schema for training plan response."""

    id: UUID
    organization_id: UUID
    generated_by: str
    model_version: Optional[str] = None
    confidence: Optional[float] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class TrainingPlanWithTasks(TrainingPlanResponse):
    """Schema for training plan with tasks count."""

    tasks_count: int = Field(0, description="Number of tasks in the plan")
    completed_tasks: int = Field(0, description="Number of completed tasks")
    adherence_pct: float = Field(0.0, description="Overall adherence percentage")


class TrainingPlanListResponse(BaseModel):
    """Schema for training plan list response with pagination."""

    plans: list[TrainingPlanResponse]
    total: int
    page: int
    page_size: int
    pages: int


# ============================================
# PLAN TASK SCHEMAS
# ============================================


class PlanTaskBase(BaseModel):
    """Base plan task schema."""

    plan_id: UUID = Field(..., description="Training plan ID")
    area: TrainingArea = Field(..., description="Training area")
    title: str = Field(..., min_length=1, max_length=255, description="Task title")
    description: Optional[str] = Field(None, description="Task description")
    target_metric: Optional[str] = Field(None, description="Target metric (e.g., 'km', 'passing_accuracy')")
    target_value: Optional[float] = Field(None, description="Target value")
    target_unit: Optional[str] = Field(None, description="Target unit")
    scheduled_date: Optional[date] = Field(None, description="Scheduled date")
    priority: int = Field(3, ge=1, le=5, description="Priority (1-5)")


class PlanTaskCreate(PlanTaskBase):
    """Schema for creating a plan task."""

    organization_id: UUID = Field(..., description="Organization ID")


class PlanTaskUpdate(BaseModel):
    """Schema for updating a plan task."""

    area: Optional[TrainingArea] = None
    title: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    target_metric: Optional[str] = None
    target_value: Optional[float] = None
    target_unit: Optional[str] = None
    scheduled_date: Optional[date] = None
    priority: Optional[int] = Field(None, ge=1, le=5)
    status: Optional[TaskStatus] = None
    completion_pct: Optional[float] = Field(None, ge=0, le=100)


class PlanTaskResponse(PlanTaskBase):
    """Schema for plan task response."""

    id: UUID
    organization_id: UUID
    status: TaskStatus
    completion_pct: float
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


# ============================================
# PLAN ADHERENCE SCHEMAS
# ============================================


class PlanAdherenceBase(BaseModel):
    """Base plan adherence schema."""

    task_id: UUID = Field(..., description="Plan task ID")
    player_id: UUID = Field(..., description="Player ID")
    completed_date: date = Field(..., description="Completion date")
    status: TaskStatus = Field(..., description="Task status")
    actual_value: Optional[float] = Field(None, description="Actual value achieved")
    notes: Optional[str] = Field(None, max_length=500, description="Notes")


class PlanAdherenceCreate(PlanAdherenceBase):
    """Schema for creating adherence record."""

    organization_id: UUID = Field(..., description="Organization ID")


class PlanAdherenceUpdate(BaseModel):
    """Schema for updating adherence record."""

    status: Optional[TaskStatus] = None
    actual_value: Optional[float] = None
    notes: Optional[str] = Field(None, max_length=500)


class PlanAdherenceResponse(PlanAdherenceBase):
    """Schema for adherence response."""

    id: UUID
    organization_id: UUID
    created_at: datetime

    class Config:
        from_attributes = True


# ============================================
# PLAN GENERATION SCHEMAS
# ============================================


class PlanGenerationRequest(BaseModel):
    """Schema for generating a training plan."""

    player_id: UUID = Field(..., description="Player ID")
    week_start: date = Field(..., description="Week start date")
    week_end: date = Field(..., description="Week end date")
    target_areas: list[TrainingArea] = Field(..., description="Target training areas")
    organization_id: UUID = Field(..., description="Organization ID")
    use_ml: bool = Field(False, description="Use ML to generate plan")


# ============================================
# PLAN STATISTICS SCHEMAS
# ============================================


class PlanAdherenceStatsResponse(BaseModel):
    """Schema for plan adherence statistics."""

    plan_id: UUID
    player_id: UUID
    week_start: date
    week_end: date

    # Task stats
    total_tasks: int = 0
    completed_tasks: int = 0
    partial_tasks: int = 0
    pending_tasks: int = 0
    skipped_tasks: int = 0

    # Adherence
    overall_adherence_pct: float = 0.0
    avg_completion_pct: float = 0.0

    # By area
    adherence_by_area: dict[str, float] = {}


class PlayerPlanHistoryResponse(BaseModel):
    """Schema for player plan history."""

    player_id: UUID
    player_name: str

    # Overall stats
    total_plans: int = 0
    total_tasks: int = 0
    completed_tasks: int = 0
    overall_adherence_pct: float = 0.0

    # Recent plans
    recent_plans: list[TrainingPlanWithTasks] = []
