"""
Application configuration using Pydantic Settings.
Loads from environment variables and .env file.
"""

from functools import lru_cache
from typing import Literal

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from environment."""

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # App
    APP_ENV: str = "production"
    APP_NAME: str = "Football Club Platform"
    API_VERSION: str = "v1"
    DEBUG: bool = False

    # Security
    JWT_SECRET: str = Field(..., min_length=32)
    JWT_ALGORITHM: str = "HS256"
    JWT_EXPIRES_MIN: int = 30
    JWT_REFRESH_EXPIRES_DAYS: int = 7
    BCRYPT_ROUNDS: int = 12

    # CORS Configuration
    # IMPORTANT: Port 3001 is RESERVED for pythonpro - DO NOT USE
    # Frontend should use port 3000 (FCP_WEB_PORT=3000)
    ALLOWED_ORIGINS: str = "http://localhost:3000"
    CORS_ALLOW_CREDENTIALS: bool = True
    CORS_MAX_AGE: int = 3600

    @field_validator("ALLOWED_ORIGINS")
    @classmethod
    def parse_origins(cls, v: str) -> list[str]:
        """Parse comma-separated list of allowed origins for CORS."""
        return [origin.strip() for origin in v.split(",")]

    # Database
    DATABASE_URL: str
    DB_POOL_SIZE: int = 20
    DB_MAX_OVERFLOW: int = 10
    DB_ECHO: bool = False

    # Redis
    REDIS_URL: str = "redis://redis:6379/0"
    REDIS_MAX_CONNECTIONS: int = 50
    QUEUE_BACKEND: Literal["rq", "celery"] = "rq"

    # Storage
    STORAGE_BACKEND: Literal["local", "s3"] = "local"
    STORAGE_LOCAL_PATH: str = "/data/storage"
    UPLOAD_MAX_SIZE_MB: int = 500

    # S3/MinIO
    S3_ENDPOINT_URL: str | None = None
    S3_BUCKET: str = "football-media"
    S3_ACCESS_KEY: str | None = None
    S3_SECRET_KEY: str | None = None
    S3_REGION: str = "eu-south-1"
    S3_USE_SSL: bool = False

    # Video Processing
    ENABLE_GPU: bool = False
    POSE_BACKEND: Literal["mediapipe", "yolo_pose"] = "mediapipe"
    VIDEO_KEYFRAME_SEC: int = 2
    VIDEO_PROCESS_TIMEOUT_SEC: int = 1800
    FFMPEG_THREADS: int = 4
    HEATMAP_FIELD_LENGTH_M: int = 105
    HEATMAP_FIELD_WIDTH_M: int = 68

    # Machine Learning
    USE_NEW_MODEL: bool = False
    ML_MODEL_VERSION: str = "1.0.0"
    ML_RETRAIN_MIN_SAMPLES: int = 100
    ML_DRIFT_PSI_WARN: float = 0.1
    ML_DRIFT_PSI_ALERT: float = 0.25
    ML_DRIFT_MAE_DEGRADE_THRESHOLD: float = 0.2
    ML_CALIBRATION_METHOD: Literal["isotonic", "platt"] = "isotonic"
    ML_SHAP_TIMEOUT_SEC: int = 30

    # Performance Thresholds
    PERF_THRESHOLD_LOW: float = 45.0
    PERF_THRESHOLD_HIGH: float = 70.0

    # Reports & PDF
    PDF_BACKEND: Literal["weasyprint", "reportlab"] = "weasyprint"
    PDF_LOCALE: str = "it-IT"
    PDF_TIMEZONE: str = "Europe/Rome"
    PDF_FOOTER_TEXT: str = "Generated by Football Club Platform"
    PDF_CACHE_HOURS: int = 24
    PDF_DPI: int = 150
    MATPLOTLIB_STYLE: str = "seaborn-v0_8-darkgrid"

    # SMTP (Optional)
    SMTP_ENABLED: bool = False
    SMTP_HOST: str = "smtp.gmail.com"
    SMTP_PORT: int = 587
    SMTP_USER: str | None = None
    SMTP_PASSWORD: str | None = None
    SMTP_TLS: bool = True
    SMTP_FROM_NAME: str = "Football Club Platform"
    SMTP_FROM_EMAIL: str = "noreply@example.com"

    # VAPID Keys for Web Push (Required for browser notifications)
    VAPID_PUBLIC_KEY: str | None = None
    VAPID_PRIVATE_KEY: str | None = None

    # Frontend URL for notifications
    FRONTEND_URL: str = "http://localhost:3000"

    # Cron / Scheduled Jobs
    CRON_WEEKLY_STAFF_BRIEF: str = "0 8 * * 1"
    MODEL_RETRAIN_CRON: str = "0 3 * * 1"
    DRIFT_CHECK_CRON: str = "0 4 * * *"
    CACHE_CLEANUP_CRON: str = "0 2 * * *"

    # GDPR & Privacy
    DATA_RETENTION_DAYS: int = 1095  # 3 years
    ANONYMIZE_EXPORTS: bool = True
    AUDIT_LOG_RETENTION_DAYS: int = 2555  # 7 years
    CONSENT_REQUIRED: bool = True
    MINOR_AGE_THRESHOLD: int = 18

    # Security
    RATE_LIMIT_PER_MINUTE: int = 60
    RATE_LIMIT_BURST: int = 100
    SESSION_COOKIE_SECURE: bool = True
    SESSION_COOKIE_HTTPONLY: bool = True
    SESSION_COOKIE_SAMESITE: str = "lax"

    # Observability
    ENABLE_METRICS: bool = True
    METRICS_PORT: int = 9090
    SENTRY_DSN: str | None = None
    SENTRY_ENVIRONMENT: str = "production"
    SENTRY_TRACES_SAMPLE_RATE: float = 0.1
    LOG_LEVEL: str = "INFO"
    WORKERS: int = 4

    # OpenTelemetry
    OTEL_ENABLED: bool = True
    OTEL_EXPORTER_OTLP_ENDPOINT: str = "http://otel-collector:4317"
    OTEL_SERVICE_NAME: str = "football-club-platform-api"
    OTEL_TRACES_EXPORTER: Literal["otlp", "console", "none"] = "otlp"
    OTEL_METRICS_EXPORTER: Literal["otlp", "console", "none"] = "otlp"

    # MLflow
    MLFLOW_TRACKING_URI: str = "http://mlflow:5000"
    MLFLOW_EXPERIMENT_NAME: str = "football-club-platform-injury-prediction"
    MLFLOW_REGISTRY_URI: str | None = None

    # Benchmark
    BENCHMARK_ENABLED: bool = True
    BENCHMARK_OPT_IN_DEFAULT: bool = False
    BENCHMARK_MIN_SAMPLES: int = 10
    BENCHMARK_CACHE_DAYS: int = 7

    # Multi-Tenancy
    TENANT_ISOLATION_STRICT: bool = True
    DEFAULT_TENANT_QUOTA_PLAYERS: int = 50
    DEFAULT_TENANT_QUOTA_STORAGE_GB: int = 10


@lru_cache
def get_settings() -> Settings:
    """Get cached settings instance."""
    return Settings()  # type: ignore


# Global settings instance
settings = get_settings()
