#!/usr/bin/env python3
"""Seed script - Add 5 wellness records for each existing player."""

import sys
from datetime import date, timedelta
from pathlib import Path
from random import uniform, randint
from uuid import uuid4

# Add backend to path only if running outside container
try:
    import app
except ImportError:
    sys.path.insert(0, str(Path(__file__).parent.parent / "backend"))

from sqlalchemy import create_engine
from sqlalchemy.orm import Session as OrmSession

from app.config import settings
from app.models import Player, WellnessData

database_url = settings.DATABASE_URL.replace("postgresql+asyncpg://", "postgresql+psycopg://")
engine = create_engine(database_url, echo=False)

with OrmSession(engine) as session:
    print("=== ADDING 5 WELLNESS RECORDS FOR EACH PLAYER ===\n")

    # Get all players using SQLAlchemy query
    players_query = session.query(Player).filter(Player.is_active == True)

    players_count = 0
    # Create 5 wellness records for each player
    total_records = 0
    today = date.today()

    for player in players_query:
        print(f"\nCreating wellness records for Player ID: {player.id}")

        for i in range(5):
            # Create records for the last 5 days (going backwards)
            record_date = today - timedelta(days=i)

            # Check if wellness record already exists for this player on this date
            existing = session.query(WellnessData).filter(
                WellnessData.player_id == player.id,
                WellnessData.date == record_date
            ).first()

            if existing:
                print(f"  ⚠ Record for {record_date} already exists, skipping...")
                continue

            # Generate realistic but varied wellness data
            # Better values for more recent days (less fatigue)
            fatigue_factor = i * 0.3  # Recent days = less fatigue

            wellness = WellnessData(
                id=uuid4(),
                date=record_date,
                player_id=player.id,
                organization_id=player.organization_id,

                # Sleep (7-9 hours, quality 3-5)
                sleep_hours=round(uniform(7.0, 9.0), 1),
                sleep_quality=randint(3, 5),

                # Recovery metrics
                hrv_ms=round(uniform(60.0, 90.0), 1),  # Heart Rate Variability
                resting_hr_bpm=randint(55, 70),  # Resting heart rate
                doms_rating=max(1, min(5, randint(2, 4) + int(fatigue_factor))),  # Muscle soreness

                # Perceived state (1-5 scale, better for recent days)
                fatigue_rating=max(1, min(5, randint(2, 4) + int(fatigue_factor))),
                stress_rating=randint(2, 4),
                mood_rating=max(1, min(5, randint(3, 5) - int(fatigue_factor))),
                motivation_rating=max(1, min(5, randint(3, 5) - int(fatigue_factor))),

                # Hydration
                hydration_rating=randint(3, 5),

                # Session RPE (if training day - assume training every other day)
                srpe=randint(5, 8) if i % 2 == 0 else None,
                session_duration_min=90 if i % 2 == 0 else None,
                training_load=round(uniform(350, 600), 1) if i % 2 == 0 else None,

                notes=f"Autogenerated wellness data - Day {i+1}"
            )

            session.add(wellness)
            total_records += 1
            print(f"  ✓ {record_date}: Sleep {wellness.sleep_hours}h, "
                  f"Fatigue {wellness.fatigue_rating}/5, Mood {wellness.mood_rating}/5")

        players_count += 1

    session.commit()

    print("\n" + "="*60)
    print("✅ WELLNESS DATA SEEDING COMPLETED!")
    print("="*60)
    print(f"\n📊 Summary:")
    print(f"   • Players processed: {players_count}")
    print(f"   • Wellness records created: {total_records}")
    print(f"   • Date range: {today - timedelta(days=4)} to {today}")
    print(f"\n🌐 Access wellness data:")
    print(f"   • API: http://localhost:8000/docs#/Wellness")
    print(f"   • Endpoint: GET /api/v1/wellness/")
    print()
